[33기 이예은] Django Project Initial Setting
wecode-bootcamp-korea/33-1st-Lulusher-backend pull request #1
Opened 2022-05-23 10:09 UTC by yaeyunle

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- 장고 초기 세팅 

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장고 초기 세팅

2022-05-23 10:19 UTC, lordmyshepherd requested changes
.pyc 확장자를 가진 파일들이 많이 올라왔습니다. Github에 올라오지 않도록 지워주시고 커밋해서 올려주세요.
추가로 gitignore 파일에도 추가해 주세요!

2022-05-23 10:19 UTC, lordmyshepherd commented on luluisher/my_settings.py
> +SECRET_KEY = 'django-insecure-@t%1gq4w=5ye3=eh2qho$s2x%15e0r=h$onvse9!eyyf^jdtha'
my_settings.py 파일이 그대로 노출되고 있습니다. 환경변수 관리용 파일은 github에 올라오지 않도록 삭제하고 다시 커밋해서 올려주세요!

2022-05-23 10:19 UTC, lordmyshepherd commented on luluisher/requirements.txt
> +
빈 줄이 없도록 지워주세요.

2022-05-24 01:14 UTC, bigfanoftim requested changes
예은님! 여전히 GitHub에 올라오면 안될 파일들이 올라와있습니다!!
항상 PR을 생성하면 `Files changed`를 들어가 직접 확인해보셔야 합니다.

현재 `.gitignore`에 잘 추가가 되었는데도 GitHub에 계속해서 보이는 이유는 이미 추가 전에 커밋했기 때문입니다! git cache 삭제하는 명령어 찾아보시고 다시 올려주세요.

2022-05-24 08:35 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-05-24 08:36 UTC, merged