[33기 최혜인, 이예은] luluisher 모델링 작성
wecode-bootcamp-korea/33-1st-Lulusher-backend pull request #2
Opened 2022-05-25 08:45 UTC by yaeyunle

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- users app, products app 모델링 작성 

<br />

## :: 기타 질문 및 특이 사항
- ERD 링크 : https://dbdiagram.io/d/628c56adf040f104c182d58d

2022-05-25 10:57 UTC, lordmyshepherd requested changes

2022-05-25 10:57 UTC, lordmyshepherd commented on luluisher/products/models.py
> +    product_name       = models.CharField(max_length=200)
product_name -> name 으로 수정하는게 좋을 것 같습니다.
이유는 이미 Product class의 member 변수로 선언되어 있기 때문에 product_를 붙여서 변수를 길게 만들 필요가 없어 보입니다!

2022-05-25 10:57 UTC, lordmyshepherd commented on luluisher/products/models.py
> +class Product_Activity(models.Model):
class명은 CamelCase로 만드는 것이 컨벤션입니다.

```suggestion
class ProductActivity(models.Model):
```

2022-05-25 10:57 UTC, lordmyshepherd commented on luluisher/products/models.py
> +    product_name  = models.ManyToManyField('Product', through="Product_Activity")
ManyToMany 필드를 사용하실 경우에는 ManyToMany 관계가 걸린 컬럼을 복수로 지정하셔야 가독성 좋은 코드를 작성할 수 있습니다.

```suggestion
    products  = models.ManyToManyField('Product', through="Product_Activity")
```

그 이유는 무엇일까요? 
예를 들어서, 아래와 같이 id가 1인 activity를 가져와서 activity 변수에 담아주고, 해당 activity와 관계된 모든 상품을 가져오고 싶은 경우를 가정해봅시다.

```python
activitiy = Activity.objects.get(id=1)

# before

products = activity.product_name.all()

# after

products = activity.products.all()
```

이렇듯 models을 가져다 사용하는 곳에서 가독성 좋은 코드를 작성하려면, 변수명을 만들 때 잘 고민해보고 만드셔야 합니다.
그래야만 코드가 읽기 쉬워지고 나중에 버그가 발생했을 때에도 디버깅(debug) 하기가 쉽습니다.

2022-05-25 10:57 UTC, lordmyshepherd commented on luluisher/users/models.py
> +class Cart(TimeStampModel):
Cart 테이블에는 user_id와 product_id를 동시에 unique 값을 걸어줘야 합니다.
그 이유는 무엇일까요? 고민해보고 답변 남겨주세요!

2022-05-25 10:57 UTC, lordmyshepherd commented on luluisher/users/urls.py
> +    path('/signup', SignUpView.as_view()),
Model 관련 PR인데 회원가입, 로그인 View가 올라왔네요?

하나의 PR에는 하나의 컨텍스트만 올라와야 합니다. 컨텍스트란 모델링 관련 PR이면 models.py 파일과 migarations.py 파일만 PR에 포함되어야 하는 것이죠.

PR은 이렇게 기능 단위로 잘 쪼개서 올려주셔야 코드를 리뷰하는 동료 혹은 사수가 더 좋은 피드백을 줄 수 있고, PR이 빨리 main 브렌치에 머지될 수 있습니다.

예를 들어서, models.py 파일은 main branch에 merge 해도 되는 코드인, views.py에서 계속 수정사항이 생긴다면 전체 코드가 머지가 안되는 문제가 발생합니다!

2022-05-25 10:57 UTC, lordmyshepherd commented on luluisher/users/views.py
> +class SignUpView(View):
Signup, Signin은 각각 새로운 PR로 만들어서 올려주세요-!

2022-05-25 10:57 UTC, lordmyshepherd commented on luluisher/utils.py
> +def login_decorator(func):
마찬가지입니다!

2022-05-26 02:13 UTC, yaeyunle commented on luluisher/users/models.py
> +class Cart(TimeStampModel):
user1이 product1을 장바구니에 넣고 또 다시 product1을 넣는다는 가정이라면, product1이 두번 추가되는 걸 방지하고 수량만 변경될 수 있도록 동시에 unique 값을 걸어줘야 합니다.
unique_together 또는 uniqueConstraint를 통해 unique 값을 동시에 적용시켜 줄 수 있습니다. 
(..맞나요?..)

2022-05-26 02:15 UTC, yaeyunle commented on luluisher/users/urls.py
> +    path('/signup', SignUpView.as_view()),
네 알겠습니다~!

2022-05-26 05:11 UTC, lordmyshepherd commented on luluisher/users/models.py
> +class Cart(TimeStampModel):
정확합니다! 👍🏻

2022-05-26 05:12 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-05-26 05:12 UTC, merged