[33기 최혜인, 이예은] - 회원가입 기능 구현
wecode-bootcamp-korea/33-1st-Lulusher-backend pull request #3
Opened 2022-05-26 06:09 UTC by yaeyunle

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 회원가입 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password validaton 처리 
- 해당 조건이 통과하지 못 할 경우 에러 메시지를 반환 처리 구현

2022-05-26 07:44 UTC, lordmyshepherd requested changes

2022-05-26 07:44 UTC, lordmyshepherd commented on luluisher/users/views.py
> +            password_regex = r"^(?=.{8,16}$)(?=.*[a-z])(?=.*[0-9]).*$"
정규 표현식은 상수이므로 파이썬 컨벤션에 따라서 대문자로 선언해주세요.
```python
EMAIL_REGEX = ..
PASSWORD_REGEX = ..
```

2022-05-26 07:49 UTC, bigfanoftim reviewed
혹시 해당 api 잘 호출되나요?

2022-05-27 04:25 UTC, yaeyunle commented
> 혹시 해당 api 잘 호출되나요?

이제 됩니다!

2022-05-27 05:48 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-05-27 05:48 UTC, merged