[33기 최혜인, 이예은] users app - signin view 작성
wecode-bootcamp-korea/33-1st-Lulusher-backend pull request #5
Opened 2022-05-27 06:35 UTC by yaeyunle

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 기능 구현

2022-05-27 10:20 UTC, bigfanoftim requested changes

2022-05-27 10:20 UTC, bigfanoftim commented on luluisher/users/views.py
>  from .models      import User
import문 순서를 잘 지켜서 만들어주세요.
아래와 같은 순서대로 import 하는 모듈을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

(westudy의 `coding convention` 자료를 참고해주세요.)

```python
# 파이썬 built-in 모듈
import json
import re
from datetime import datetime

# 외부 모듈
import bcrypt
import jwt
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```

2022-05-27 10:20 UTC, bigfanoftim commented on luluisher/users/views.py
> +    @login_decorator
이 함수에 login_decorator는 왜 추가되어있나요?

2022-05-27 10:20 UTC, bigfanoftim commented on luluisher/users/views.py
> +                return JsonResponse({"message" : "INVALID_USER"}, status=401)
```python
user = User.objects.get(email = email)

if not User.objects.filter(email=email).exists():
    return JsonResponse({"message": "INVALID_USER"}, status = 401)
```

`get` 메소드를 사용하여 조회했을 때 데이터베이스에 매칭되는 데이터가 없는 경우 python에서 error를 raise 합니다. 그렇기 때문에 `if not User.objects.filter(email=email).exists():` 코드가 실행될 일이 없겠죠?

그러므로 위 if문 코드는 불필요한 코드입니다. 추가로 `user = User.objects.get(email = email)` 에서 에러가 발생했을 경우에 except문에서 에러를 잡아줄 수 있도록 수정해주세요.

2022-05-27 10:20 UTC, bigfanoftim commented on luluisher/utils.py
> +            request.user = user
```suggestion
            request.user = User.objects.get(email = payload['email'])
```

2022-05-27 10:20 UTC, bigfanoftim commented on luluisher/utils.py
> +from django.http    import JsonResponse
import문 순서를 잘 지켜서 만들어주세요.
아래와 같은 순서대로 import 하는 모듈을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

(westudy의 `coding convention` 자료를 참고해주세요.)

```python
# 파이썬 built-in 모듈
import json
import re
from datetime import datetime

# 외부 모듈
import bcrypt
import jwt
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```

2022-05-27 10:20 UTC, bigfanoftim commented on luluisher/utils.py
> +from my_settings    import SECRET_KEY
```python
# views.py

from my_settings import ALGORITHM, SECRET_KEY
```

- `ALGORITHM`, `SECRET_KEY`와 같은 환경변수를 my_settings.py 파일로 관리하고 있습니다.
- my_settings.py 파일은 환경변수 관리로서의 역할만 하는 파일로서 views.py 또는 models.py에서 직접 import해서 사용하시면 views.py 파일이 my_settings.py 파일에 의존성이 생기게 됩니다.
- 만약에 환경변수를 기존의 방식인 my_settings.py가 아니라 아래와 같이 다른 방법으로 관리하게 되면 views.py처럼 기존에 my_settings.py에 의존하고 있던 모든 코드를 전부 수정해야 합니다.

```python
# settings.py

DATABASES = {
    ..
    "PASSWORD" : os.environ.get("DB_PASSWORD")
}
```

- 그러므로 my_settings.py에서 환경변수를 import해서 사용하실 때에는 지금처럼 `from my_settings import ALGORITHM, SECRET_KEY` 로 작성하는 것이 아니라 `from django.conf import settings`로 작성하여 settings.py에서 설정된 환경변수를 불러올 수 있도록 수정해주세요.

2022-05-30 07:20 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-05-30 07:20 UTC, merged